# Generated by Django 3.2.4 on 2021-10-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualFund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('query_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_phone', models.CharField(max_length=15)),
                ('query_product', models.CharField(max_length=100)),
                ('query_message', models.TextField()),
            ],
        ),
    ]
