# Generated by Django 3.2.4 on 2021-10-27 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mutualFund', '0002_customerquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquery',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
