# Generated by Django 3.2.4 on 2021-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PREIPO',
            fields=[
                ('S_No', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Script_Name', models.CharField(max_length=100)),
                ('Buying_Price', models.IntegerField()),
                ('Selling_Price', models.IntegerField()),
                ('Desc', models.TextField()),
            ],
        ),
    ]
