# Generated by Django 3.2.4 on 2021-11-07 19:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('ins_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ins_name', models.CharField(max_length=100)),
                ('ins_img', models.ImageField(upload_to='Insurance/')),
                ('desc', tinymce.models.HTMLField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
